module Refactoring::Chapter6ComposingMethods; end

require_relative 'chapter_6_composing_methods/account'
require_relative 'chapter_6_composing_methods/custom_initializers'
require_relative 'chapter_6_composing_methods/facebook'
require_relative 'chapter_6_composing_methods/gamma'
require_relative 'chapter_6_composing_methods/human'
require_relative 'chapter_6_composing_methods/item'
require_relative 'chapter_6_composing_methods/motion'
require_relative 'chapter_6_composing_methods/person'
require_relative 'chapter_6_composing_methods/pizza_boy'
require_relative 'chapter_6_composing_methods/search_criteria'
require_relative 'chapter_6_composing_methods/select'
